<a href="https://colab.research.google.com/github/idoncode/Machine_learning_revision_topics/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is Numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrics) and an assortment of routines for fast operations on arrays, including mathematical, logicalm shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogenous data types.

## Numpy arrays vs Python sequences

* NumPy arrays have a fixed size at creation, unlike Python lists(which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.
* The elements ina NumPy array are all required to be of the same data type, thus will be the same size in memory.
* NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python's built in sequences.
* A growing plethora of scientific and mathematical Python based packages are using Numpy arrays; though these typically support Python-sequences input, they convert such input to Numpy arrays prior to processing, and then often output Numpy arrays.

In [ ]:
import numpy as np
from warnings import filterwarnings
filterwarnings('ignore')

### np.array

In [ ]:
a = np.array([1,2,3])
print(f'1D array also called as a vector: {a}')
print(f'Type of the data type object: {type(a)}')

1D array also called as a vector: [1 2 3]
Type of the data type object: <class 'numpy.ndarray'>


In [ ]:
# Creating 2D and 3D arrays

two_D = np.array([[1,2,3],[2,3,4]])
three_D = np.array([[[1,2,3],[2,3,4],[4,7,9]]])
print(f'2D array also called as a matrix:\n{two_D}\n')
print(f'3D array also called as a tensor:\n{three_D}\n')

2D array also called as a matrix:
[[1 2 3]
 [2 3 4]]

3D array also called as a tensor:
[[[1 2 3]
  [2 3 4]
  [4 7 9]]]



In [ ]:
# Changing datatypes of numpy arrays

a = np.array([1,2,3],dtype = int)
print(f'Int type: \n{a}\n')
a = np.array([1,2,3],dtype = float) # <-- used most
print(f'Float type: \n{a}\n')
a = np.array([1,2,3],dtype = complex)
print(f'Complex type: \n{a}\n')
a = np.array([1,2,0],dtype = bool) ## Treating numbers as True
print(f'Boolean type: \n{a}\n')

Int type: 
[1 2 3]

Float type: 
[1. 2. 3.]

Complex type: 
[1.+0.j 2.+0.j 3.+0.j]

Boolean type: 
[ True  True False]



### np.arange

(functions like range in normal python)

In [ ]:
np.arange(1,11) # prints 1 to 10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### np.reshape

In [ ]:
print(f'Reshaping the np array of 10 elements in 2x5 shape\n {np.arange(1,11).reshape(2,5)}\n')
print(f'Reshaping the np array of 10 elements in 5x2 shape\n {np.arange(1,11).reshape(5,2)}\n')

Reshaping the np array of 10 elements in 2x5 shape
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

Reshaping the np array of 10 elements in 5x2 shape
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]



### np.ones and np.zeros

Creating np array where array is filled with zeros/ones when you provide the shape

In [ ]:
print(f'Numpy ones:\n{np.ones((5,3))}\n')
print(f'Numpy zeros:\n{np.zeros((5,3))}\n')

Numpy ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Numpy zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



### np.random.random

Will generate values between 0-1

In [ ]:
np.random.random((3,3))

array([[0.2862365 , 0.82472549, 0.428239  ],
       [0.87791864, 0.5346466 , 0.97245101],
       [0.90711569, 0.49337975, 0.78631116]])

### np.linspace

Generates **Linearly spaced** (equal distance) numbers withing the given number range

* first value: lower limit
* second value: upper limit
* third value: length (how many numbers)

In [ ]:
np.linspace(-10, 10, 10, dtype = int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

### np.identity

Creates an identity matrix

**Identity matrix** has all the diagonal elements as 1 and rest everything is 0

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [ ]:
a = np.arange(10, dtype = np.int32)
a = np.arange(1, 13, dtype = int).reshape(4,3)
print(f'Generating numbers 1-12 as integers and reshaping as 4x3:\n{a}\n')

Generating numbers 1-12 as integers and reshaping as 4x3:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]



In [ ]:
a = np.random.random(16).reshape(4,2,2)
a

array([[[0.70599487, 0.94458922],
        [0.76404194, 0.52337401]],

       [[0.74266096, 0.40217348],
        [0.32892577, 0.77514032]],

       [[0.673926  , 0.75349604],
        [0.23112887, 0.23012322]],

       [[0.87656241, 0.28509248],
        [0.43869541, 0.08008648]]])

### ndim, shape, size, itemsize

* ndim: Outputs the number of dimensions of that array
* shape: Outputs the dimension shape of the array
* size: Outputs the total number of elements that the array can hold
* itemsize: Length of one array element in bytes.

In [ ]:
a.ndim

3

In [ ]:
a.shape

(4, 2, 2)

In [ ]:
a.size

16

In [ ]:
a.itemsize

8

### dtype

Default numpy datatype is float64 and int64

In [ ]:
print(f'{np.array([1,2,3]).dtype}')
print(f'{np.array([1,2,3], dtype = np.int32).dtype}')
print(f'{np.array([1,2,3], dtype = np.float32).dtype}')

int64
int32
float32


### Changing Datatype

`astype` is used to change from one datatype to another

In [ ]:
print(f'Initial data type: {a.dtype}\n')
a.astype(np.int32)
print(f'After chaning: {a.dtype}\n')

Initial data type: float64

After chaning: float64



## Array Operations

### Scalar/Arithmetic operations, Vector operations

In [ ]:
# Scalar Operations
a1 = np.arange(10,20, dtype = np.int32)
print(f'Initial array:\n{a1}\n')
print(f'Multiplying each element with 2:\n{a1 * 2}\n')
print(f'Squaring each element:\n{a1 ** 2}\n')
print(f'Checking boolean conditions:\n{a1 == 15}') # relational operation

Initial array:
[10 11 12 13 14 15 16 17 18 19]

Multiplying each element with 2:
[20 22 24 26 28 30 32 34 36 38]

Squaring each element:
[100 121 144 169 196 225 256 289 324 361]

Checking boolean conditions:
[False False False False False  True False False False False]


In [ ]:
# Vector operations
a1 = np.arange(1, 11).reshape(5,2)
a2 = np.arange(11,21).reshape(5,2)
print(f'Initial matrices:\na1\n{a1}\na2\n{a2}\n')
print(f'Vector multiplication of these two:\n{a2 * a1}\n')

Initial matrices:
a1
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
a2
[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]

Vector multiplication of these two:
[[ 11  24]
 [ 39  56]
 [ 75  96]
 [119 144]
 [171 200]]



In [ ]:
a1 = np.round(np.random.random((3,3)) * 100).astype(np.int32)
a1

array([[47, 98, 57],
       [10, 51, 15],
       [69, 18, 76]], dtype=int32)

### Min / Max / Sum / Prod

axis: One which axes should you multiply
* 0 is columns and 1 is rows

In [ ]:
a = np.array([[1,2,3],[2,3,4],[2,4,1]])
print(f'Initial Matrix:\n{a}\n')
print(f'Multiplication product of columns: {np.prod(a,axis=0)}\n')
print(f'Multiplication product of rows: {np.prod(a,axis=1)}\n')
print(f'Sum of rows: {np.sum(a, axis=1)}\n')
print(f'Max of columns: {np.max(a, axis=0)}\n')
print(f'Min of rows: {np.min(a, axis=1)}\n')

Initial Matrix:
[[1 2 3]
 [2 3 4]
 [2 4 1]]

Multiplication product of columns: [ 4 24 12]

Multiplication product of rows: [ 6 24  8]

Sum of rows: [6 9 7]

Max of columns: [2 4 4]

Min of rows: [1 2 1]



Mean / Median / Std / Var

In [ ]:
print(f'Mean of rows: {np.mean(a, axis=1)}\n')
print(f'Mediam of columns: {np.median(a, axis=0)}\n')
print(f'Std of rows: {np.std(a, axis=1)}\n')
print(f'Var of columns: {np.var(a, axis=0)}\n')

Mean of rows: [2.         3.         2.33333333]

Mediam of columns: [2. 3. 3.]

Std of rows: [0.81649658 0.81649658 1.24721913]

Var of columns: [0.22222222 0.66666667 1.55555556]



### Trigonometric functions

In [ ]:

print(f'Initial matrix:\n{a}\n')
print(f'Matrix after Sin function:\n{np.sin(a)}\n')

Initial matrix:
[[1 2 3]
 [2 3 4]
 [2 4 1]]

Matrix after Sin function:
[[ 0.84147098  0.90929743  0.14112001]
 [ 0.90929743  0.14112001 -0.7568025 ]
 [ 0.90929743 -0.7568025   0.84147098]]



### Dot product

Check the shape 3x4 and 4x3 matrices, since 4 is same, then only dot product is possible

In [133]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(4,3)
print(f'a1:\n{a1}\n')
print(f'a2:\n{a2}\n')
print(f'Dot product of a1 and a2:\n{np.dot(a1,a2)}')

a1:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

a2:
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]

Dot product of a1 and a2:
[[114 120 126]
 [378 400 422]
 [642 680 718]]


### Log and exponents

In [136]:
print(f'Exponents of a1:\n{np.exp(a1)}\n')
print(f'Logs of a1:\n{np.log(a1)}\n')

Exponents of a1:
[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]

Logs of a1:
[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]



### Round / Floor / Ceil

In [142]:
a = np.random.random((2,3)) * 100
print(f"Initial array:\n{a}\n")
print(f'Rounded off array:\n{np.round(a)}\n')
print(f"Ceiled array:\n{np.ceil(a)}\n")
print(f"Floored array:\n{np.floor(a)}\n")

Initial array:
[[29.72952834 88.13308903 91.52457546]
 [79.92693199 48.47794264 98.48114627]]

Rounded off array:
[[30. 88. 92.]
 [80. 48. 98.]]

Ceiled array:
[[30. 89. 92.]
 [80. 49. 99.]]

Floored array:
[[29. 88. 91.]
 [79. 48. 98.]]



### Indexing and Slicing

In [146]:
a = np.arange(1,37).reshape(3,4,3)
print(f'Inital array:\n{a}\n')

Inital array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]



In [155]:
print(f'To take out five: {a[0,1,1]}')
print(f'Another way: {a[0][1][1]}')

To take out five: 5
Another way: 5


In [159]:
print(f'To print the middle matrix array:\n{a[1,:,:]}')

To print the middle matrix array:
[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]


In [161]:
print(f'To print 2nd row of the middle matrix array:\n{a[1,1,:]}')

To print 2nd row of the middle matrix array:
[16 17 18]


### Transposing

In [164]:
print(f'Initial matrix array:\n{a}\n')
print(f'Transposed matrix array:\n{np.transpose(a)}\n')

Initial matrix array:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]

Transposed matrix array:
[[[ 1 13 25]
  [ 4 16 28]
  [ 7 19 31]
  [10 22 34]]

 [[ 2 14 26]
  [ 5 17 29]
  [ 8 20 32]
  [11 23 35]]

 [[ 3 15 27]
  [ 6 18 30]
  [ 9 21 33]
  [12 24 36]]]



### Ravel

This will unravel all the dimensions and make it 1D

In [166]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

### Stacking

In [170]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
print(f'Array 1:\n{a1}\n')
print(f'Array 2:\n{a2}\n')
# horzontal stacking
a3 = np.hstack((a1,a2))
print(f'Horizontal stacking:\n{a3}\n')
# vertical stacking
a4 = np.vstack((a1,a2))
print(f'Vertical stacking:\n{a4}\n')
## Printing the shapes
print(f'Shape of Array 1:\n{a1.shape}\nShape of Array 2:\n{a2.shape}\nShape of Horizontal Stack: {a3.shape}\nShape of Vertical Stack: {a4.shape}\n')

Array 1:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Array 2:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Horizontal stacking:
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]

Vertical stacking:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Shape of Array 1:
(3, 4)
Shape of Array 2:
(3, 4)
Shape of Horizontal Stack: (3, 8)
Shape of Vertical Stack: (6, 4)



### Splitting

In [178]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(1,25).reshape(6,4)
print(f'Array 1:\n{a1}\n')
print(f'Array 2:\n{a2}\n')
# horzontal splitting
a3 = np.hsplit(a1,2)
print(f'Horizontal splitting:\n{a3}\n')
# vertical splitting
a4 = np.vsplit(a1,3)
print(f'Vertical splitting:\n{a4}\n')

Array 1:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Array 2:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Horizontal splitting:
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]

Vertical splitting:
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

